### ISSUE TITLE
parse_wikipedia_tables.py - running into UnicodeEncodeError

### ISSUE THREAD

**Issue by slashTPA** [P1sec/MCC_MNC#1]
Hi there, 

using "python parse_wikipedia_tables.py -j -p" I run into following issue:

[+] parsed 4 MNC entries for MCC 746
[+] parsed 5 MNC entries for MCC 748
[+] parsed 5 MNC entries for MCC 734
[+] 2798 MCC MNC entries for 2758 unique MCC MNC
> duplicate borders entry for France
> duplicate borders entry for United Kingdom
[+] raw/wikip_iso3166.json file generated
[+] raw/wikip_mcc.json file generated
[+] raw/wikip_mnc.json file generated
[+] raw/wikip_msisdn.json file generated
[+] raw/wikip_country.json file generated
[+] raw/wikip_territory.json file generated
[+] raw/wikip_borders.json file generated
[+] raw/wikip_iso3166.py file generated
**Traceback (most recent call last):
  File "parse_wikipedia_tables.py", line 705, in <module>
    sys.exit(main())
  File "parse_wikipedia_tables.py", line 694, in main
    generate_python(L_mcc, PATH_PRE + 'wikip_mcc.py', [URL_MCC], URL_LICENSE)
  File "parse_wikipedia_tables.py", line 667, in generate_python
    fd.write('%s = \\\n%s\n' % (varname, pp.pformat(d)))
  File "C:\Users\...\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u010c' in position 5088: character maps to <undefined>**

Any idea? Thanks.

**Comment by mitshell** [comment]
Which Python version are you using ?

**Comment by slashTPA** [comment]
I'm using **Python 3.8.5 on a WIN10** laptop. The issue **_doesn't happen on my linux machine using Python 3.8.3_**

The issue is with:

(base) C:\Users\...\OneDrive\__SNDBOX\MCC_MNC>python **parse_itut_bulletins.py** -j -p
> error occured during MNC extraction: 'charmap' codec can't decode byte 0x81 in position 80600: character maps to <undefined>

**Comment by p1-bmu** [comment]
Commit https://github.com/P1sec/MCC_MNC/commit/c3ecd6300876ab2e3ca2cff6639c0aa1e3cc887f may fix your issue on Windows (but I did not test it on Windows).
Otherwise, the worldfactbook extraction is currently broken as the CIA changed the entire website layout.
